opt_in_rules:
- empty_count
- empty_string
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - /Modules/CoreModules/SpotifyLogin/
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 80
    error: 200
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 200
    error: 400
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
